### ISSUE TITLE
Chromium version and status

### ISSUE THREAD

**Issue by Alex313031** [win32ss/supermium-electron#3]
What Chromium version is this based on, and does it work on Win7 SP1 yet?

**Comment by MiraakThuri** [comment]
This is based on Supermium https://github.com/win32ss/supermium (fork of chromium for vista, 7 and 8x, currently at version 117)

And yes it's currently working on Vista and later but it's still a pretty early release, so don't expect alot of programs to work

**Comment by Alex313031** [comment]
@win32ss You should base it on Electron 27 stable with Chromium 118 stable [27.0.3](https://releases.electronjs.org/release/v27.0.3), not the tip of tree nightly release. More stability so people could actually use it in their apps. I would use it in some of my apps if it wasnt nightly versions.

**Comment by win32ss** [comment]
Now that fewer breaking changes are occurring to both Chromium and Electron, I think it would make sense to make both switch to stable branches.

**Comment by win32ss** [comment]
Supermium is ceasing cooperation with all Thorium-related projects effectively immediately.

Tests with CEF and Electron-based software are to be planned later this month.
