### ISSUE TITLE
[Feature Request]: Option to specify an external icon for the titlebar/taskbar/etc. icon.

### ISSUE THREAD

**Issue by KandiPanda** [win32ss/supermium-electron#4]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Supermium-Electron uses the built-in default Electron icon. (Which in of itself is fine, *but...*) When using it to replace an existing app's Electron, it would be nice for the window to have that app's icon in the titlebar/taskbar/etc., rather than the generic Electron icon. (Especially if running multiple different Electron apps with it at the same time, to tell them apart in the taskbar with just a glance over the icon.)

### Proposed Solution

- Add a `-icon <icon_file>` launch flag to specify what icon to use. (This approach would be particularly useful for someone also using one Supermium-Electron install to launch multiple things by specifying different `resources` folders.) 
- If the flag is not used, check in the launch directory for an `app.ico` to use (much like Discord has, IIRC?). 
- If that is not present either, *then* fall back to using the internal default icon.

### Alternatives Considered

I already tried using a resource editor to replace the icon in the exe of the testing release. That... did *not* go well. 

Even if it *had* worked for me, hardcoding one icon in (either by building it with that icon substituted in place of of the default `icon.png` file, or by editing the new icon into the existing exe) would be less useful if someone wanted to use one install of Supermium-Electron pointed at different `resources` folders to launch different Electron apps with. 

Being able to specify (or otherwise supply) a replacement icon without having to build with the substituted icon or to resource edit the exe would also be much more user-friendly.

### Additional Information

I *did* look to see if there was already any way to specify this with Electron, but all I could find were ways for app developers to specify what icon would be built-in, and/or what code to use to have an app set its window icon from an internal image. 

If there's already something that I missed that's closer to what I'm looking for (or even a workaround that has a prebuilt app run a script at launch to switch to using an external icon), I'd be happy to hear more about it.

**Comment by win32ss** [comment]
Seems feasible, as we can obviously review the contents of the command line when registering the window class for the windows that appear on the taskbar.
